
services:
  ui:
    # build: ./ui
    image: taleemhelp/ui:0.9.11
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_SOUND_BASE_URL=https://taleem-media.blr1.cdn.digitaloceanspaces.com/sound
      - VITE_IMAGES_BASE_URL=https://taleem-media.blr1.cdn.digitaloceanspaces.com
      - VITE_DEFAULT_AUDIO=/music.opus
